---
  specifications:
    input:
      - arch
    
  repositories:
    - name: Almirah.Code
      path: ../Almirah.Code/lib
    - name: Almirah.Spec
      path: ../Almirah.Code/spec

  planning:
    start_date: 12-05-2026
